---
# tasks file for roles/folders

- name: ftp directory
  file:
    path: ~/jalopez1/ftp
    state: directory
    owner: nobody
    group: nogroup
    mode: '0555'

- name: create files for ftp directory
  file:
    path: ~/jalopez1/ftp/files
    state: directory
    owner: jalopez1
    group: jalopez1

- name: copy vsftpd.conf
  copy:
    src: vsftpd.conf
    dest: /etc/vsftpd.conf
  register: vsftpd_config

- name: restart vsftpd.conf
  service:
    name: vsftpd
    state: restarted
  when: vsftpd_config.changed
