---
# tasks file for roles/elk2
# Please use this command "ansible-galaxy collection install containers.podman"
- name: Install docker
  yum:
    name: docker
    state: latest
    update_cache: yes

- name: pull elasticsearch image
  containers.podman.podman_image:
    name: docker.elastic.co/elasticsearch/elasticsearch:7.10.1

- name: create elasticsearch network
  containers.podman.podman_network:
    name: elastic
  become: true

- name: Create elasticsearch container
  containers.podman.podman_containers:
    containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        state: present
        ports:
          - "9400:9400"
        networks:
          - name: elastic

- name: Pull kibana image
  containers.podman.podman_image:
    name: docker.elastic.co/kibana/kibana:7.10.1

- name: Create kibana container
  containers.podman.podman_containers:
    containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.10.1
        state: present
        ports:
          - "5602:5602"
        networks:
          - name: elastic

- name: pull logstash image
  containers.podman.podman_image:
    name: docker.elastic.co/logstash/logstash:7.10.1

- name: Create logstash container
  containers.podman.podman_containers:
    containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.10.1
        state: present
        ports:
          - "5045:5045"
        networks:
          - name: elastic
