 ---
 # tasks file for roles/mysql

 - name: Installing MySQL [MySQL]
   apt:
     name: mysql-server
     state: latest
     update_cache: yes

 - name: MySQL [index]
   copy:
     content: "jalopez"
     dest: /var/www/html/indexone.html
     owner: root
     group: root
     mode: '0664'
   register: mysqlservice_index

 - name: Starting [MySQL Service]
   service:
     name: mysql
     state: restarted
     enabled: yes
    when: mysqlservice_index.changed
