---
# tasks file for roles/grafana_ubuntu
- name: adding grafana packages
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: adding grafana repository
  shell: echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

- name: updating ubuntu
  become: yes
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: installing grafana in ubuntu
  apt:
    name: grafana
    state: present
