---
# tasks file for roles/cetlanmt2
- name: add prometheus repo
  copy:
    src: prometheus.repo
    dest: /etc/yum.repos.d/

- name: Install prometheus
  yum:
    name: prometheus2
    state: latest
    update_cache: yes

- name: start prometheus
  service:
    name: prometheus
    state: started
