---
# tasks file for roles/osuslanmt3
- name: Install prometheus
  zypper:
    name: golang-github-prometheus-prometheus
    state: latest
    update_cache: yes

- name: Start prometheus
  service:
    name: prometheus
    state: started
