---
# tasks file for roles/plugin_centos
- name: downloading extracting nagios plugin
  unarchive:
    src: https://nagios-plugins.org/download/nagios-plugins-2.2.1.tar.gz
    dest: /tmp
    remote_src: yes

- name: configuring nagios plugins
  command: ./configure --with-nagios-user=nagios --with-nagios-group=nagiosxi
  args:
    chdir: /tmp/nagios-plugins-2.2.1

- name: configuring make
  make:
    chdir: /tmp/nagios-plugins-2.2.1

- name: configuring make install
  make:
    target: install
    chdir: /tmp/nagios-plugins-2.2.1

- name: starting and enabling nagios services
  service:
    name: nagios
    state: started
    enabled: yes
