---
# tasks file for roles/main_ubuntu
- name: downloading and extracting nagios core
  unarchive:
    src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp
    copy: no

- name: configuring nagios
  command: ./configure --with-nagios-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled
  args:
    chdir: /tmp/nagios-4.4.5

- name: configuring nagios clean
  make:
    target: clean
    chdir: /tmp/nagios-4.4.5

- name: nagios compilation
  make:
    target: all
    chdir: /tmp/nagios-4.4.5

- name: installing nagios compilation
  make:
    target: install
    chdir: /tmp/nagios-4.4.5

- name: installing nagios init
  make:
    target: install-init
    chdir: /tmp/nagios-4.4.5

- name: installing nagios config
  make:
    target: install-config
    chdir: /tmp/nagios-4.4.5

- name: installing nagios commandmode
  make:
    target: install-commandmode
    chdir: /tmp/nagios-4.4.5

- name: web interface installer
  make:
    target: install-webconf
    chdir: /tmp/nagios-4.4.5

- name: adding user account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: jalopez
    password: jalopez

- name: a2enmod cgi
  command: a2enmod cgi

- name: restarting apache2
  service:
    name: apache2
    state: restarted
