---
# tasks file for roles/docker/ubuntu
- name: Installing the pre-requisites
  become: yes
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Installing the docker file
  become: yes
  apt:
    name: docker.io
    state: latest
    update_cache: yes
  register: docker

- name: Installing the docker.py
  become: yes
  pip:
    name: docker.py
    state: latest
  when: docker.changed
