---
# tasks file for roles/install_at_ubuntu 

- name: dhcp installment at ubuntu
  apt:
    name: isc-dhcp-server
    state: latest
    update_cache: yes

- name: bind9 installment at ubuntu
  apt:
    name: bind9
    state: latest
    update_cache: yes

- name: vsftpd installment at ubuntu
  apt:
    name: vsftpd
    state: latest
    update_cache: yes
    
- name: samba installment at ubuntu
  apt:
    name: samba
    state: latest
    update_cache: yes

- name: httpd installment at ubuntu
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: mariadb installment at ubuntu
  apt:
    name: mariadb-server-10.3
    state: latest
    update_cache: yes
